name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:


jobs:
 terraform:
    name: "Terraform setup"
    runs-on: ubuntu-20.04
    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: 'us-east-1'
    
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        id: init
        run: terraform init 
      
      - name: workspace change
        run: |
              terraform workspace new dev
              terraform workspace select dev 
 
      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan 


